/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Gold Standard API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * @summary List tasks
 */
export const getApiV1TasksQueryLimitDefault = 20;
export const getApiV1TasksQueryLimitExclusiveMin = 0;
export const getApiV1TasksQueryLimitMax = 100;



export const GetApiV1TasksQueryParams = zod.object({
  "limit": zod.number().gt(getApiV1TasksQueryLimitExclusiveMin).max(getApiV1TasksQueryLimitMax).default(getApiV1TasksQueryLimitDefault),
  "cursor": zod.string().optional().describe('Opaque pagination cursor')
})

export const getApiV1TasksResponseDataItemIdRegExp = new RegExp('^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$');
export const getApiV1TasksResponseDataItemDueDateOneRegExp = new RegExp('^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z|([+-](?:[01]\\d|2[0-3]):[0-5]\\d)))$');
export const getApiV1TasksResponseDataItemCreatedAtRegExp = new RegExp('^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z|([+-](?:[01]\\d|2[0-3]):[0-5]\\d)))$');
export const getApiV1TasksResponseDataItemUpdatedAtRegExp = new RegExp('^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z|([+-](?:[01]\\d|2[0-3]):[0-5]\\d)))$');


export const GetApiV1TasksResponse = zod.object({
  "data": zod.array(zod.object({
  "id": zod.uuid().regex(getApiV1TasksResponseDataItemIdRegExp),
  "title": zod.string(),
  "done": zod.boolean(),
  "dueDate": zod.union([zod.iso.datetime({"offset":true}).regex(getApiV1TasksResponseDataItemDueDateOneRegExp),zod.null()]),
  "createdAt": zod.iso.datetime({"offset":true}).regex(getApiV1TasksResponseDataItemCreatedAtRegExp),
  "updatedAt": zod.iso.datetime({"offset":true}).regex(getApiV1TasksResponseDataItemUpdatedAtRegExp)
})),
  "meta": zod.object({
  "pagination": zod.object({
  "nextCursor": zod.union([zod.string(),zod.null()]),
  "hasMore": zod.boolean(),
  "limit": zod.number()
})
})
})


/**
 * @summary Create a task
 */
export const postApiV1TasksBodyTitleMax = 200;

export const postApiV1TasksBodyDueDateOneRegExp = new RegExp('^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z|([+-](?:[01]\\d|2[0-3]):[0-5]\\d)))$');


export const PostApiV1TasksBody = zod.object({
  "title": zod.string().min(1).max(postApiV1TasksBodyTitleMax).describe('Task title'),
  "dueDate": zod.union([zod.iso.datetime({"offset":true}).regex(postApiV1TasksBodyDueDateOneRegExp),zod.null()]).optional().describe('Due date, ISO 8601 UTC')
})

export const postApiV1TasksResponseDataIdRegExp = new RegExp('^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$');
export const postApiV1TasksResponseDataDueDateOneRegExp = new RegExp('^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z|([+-](?:[01]\\d|2[0-3]):[0-5]\\d)))$');
export const postApiV1TasksResponseDataCreatedAtRegExp = new RegExp('^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z|([+-](?:[01]\\d|2[0-3]):[0-5]\\d)))$');
export const postApiV1TasksResponseDataUpdatedAtRegExp = new RegExp('^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z|([+-](?:[01]\\d|2[0-3]):[0-5]\\d)))$');


export const PostApiV1TasksResponse = zod.object({
  "data": zod.object({
  "id": zod.uuid().regex(postApiV1TasksResponseDataIdRegExp),
  "title": zod.string(),
  "done": zod.boolean(),
  "dueDate": zod.union([zod.iso.datetime({"offset":true}).regex(postApiV1TasksResponseDataDueDateOneRegExp),zod.null()]),
  "createdAt": zod.iso.datetime({"offset":true}).regex(postApiV1TasksResponseDataCreatedAtRegExp),
  "updatedAt": zod.iso.datetime({"offset":true}).regex(postApiV1TasksResponseDataUpdatedAtRegExp)
})
})


/**
 * @summary Get a task by ID
 */
export const getApiV1TasksIdPathIdRegExp = new RegExp('^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$');


export const GetApiV1TasksIdParams = zod.object({
  "id": zod.uuid().regex(getApiV1TasksIdPathIdRegExp).describe('Task ID')
})

export const getApiV1TasksIdResponseDataIdRegExp = new RegExp('^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$');
export const getApiV1TasksIdResponseDataDueDateOneRegExp = new RegExp('^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z|([+-](?:[01]\\d|2[0-3]):[0-5]\\d)))$');
export const getApiV1TasksIdResponseDataCreatedAtRegExp = new RegExp('^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z|([+-](?:[01]\\d|2[0-3]):[0-5]\\d)))$');
export const getApiV1TasksIdResponseDataUpdatedAtRegExp = new RegExp('^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z|([+-](?:[01]\\d|2[0-3]):[0-5]\\d)))$');


export const GetApiV1TasksIdResponse = zod.object({
  "data": zod.object({
  "id": zod.uuid().regex(getApiV1TasksIdResponseDataIdRegExp),
  "title": zod.string(),
  "done": zod.boolean(),
  "dueDate": zod.union([zod.iso.datetime({"offset":true}).regex(getApiV1TasksIdResponseDataDueDateOneRegExp),zod.null()]),
  "createdAt": zod.iso.datetime({"offset":true}).regex(getApiV1TasksIdResponseDataCreatedAtRegExp),
  "updatedAt": zod.iso.datetime({"offset":true}).regex(getApiV1TasksIdResponseDataUpdatedAtRegExp)
})
})


/**
 * @summary Update a task
 */
export const patchApiV1TasksIdPathIdRegExp = new RegExp('^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$');


export const PatchApiV1TasksIdParams = zod.object({
  "id": zod.uuid().regex(patchApiV1TasksIdPathIdRegExp).describe('Task ID')
})

export const patchApiV1TasksIdBodyTitleMax = 200;

export const patchApiV1TasksIdBodyDueDateOneRegExp = new RegExp('^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z|([+-](?:[01]\\d|2[0-3]):[0-5]\\d)))$');


export const PatchApiV1TasksIdBody = zod.object({
  "title": zod.string().min(1).max(patchApiV1TasksIdBodyTitleMax).optional(),
  "done": zod.boolean().optional(),
  "dueDate": zod.union([zod.iso.datetime({"offset":true}).regex(patchApiV1TasksIdBodyDueDateOneRegExp),zod.null()]).optional()
}).describe('Fields to update; omitted fields are left unchanged')

export const patchApiV1TasksIdResponseDataIdRegExp = new RegExp('^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$');
export const patchApiV1TasksIdResponseDataDueDateOneRegExp = new RegExp('^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z|([+-](?:[01]\\d|2[0-3]):[0-5]\\d)))$');
export const patchApiV1TasksIdResponseDataCreatedAtRegExp = new RegExp('^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z|([+-](?:[01]\\d|2[0-3]):[0-5]\\d)))$');
export const patchApiV1TasksIdResponseDataUpdatedAtRegExp = new RegExp('^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z|([+-](?:[01]\\d|2[0-3]):[0-5]\\d)))$');


export const PatchApiV1TasksIdResponse = zod.object({
  "data": zod.object({
  "id": zod.uuid().regex(patchApiV1TasksIdResponseDataIdRegExp),
  "title": zod.string(),
  "done": zod.boolean(),
  "dueDate": zod.union([zod.iso.datetime({"offset":true}).regex(patchApiV1TasksIdResponseDataDueDateOneRegExp),zod.null()]),
  "createdAt": zod.iso.datetime({"offset":true}).regex(patchApiV1TasksIdResponseDataCreatedAtRegExp),
  "updatedAt": zod.iso.datetime({"offset":true}).regex(patchApiV1TasksIdResponseDataUpdatedAtRegExp)
})
})


/**
 * @summary Delete a task
 */
export const deleteApiV1TasksIdPathIdRegExp = new RegExp('^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$');


export const DeleteApiV1TasksIdParams = zod.object({
  "id": zod.uuid().regex(deleteApiV1TasksIdPathIdRegExp).describe('Task ID')
})

export const DeleteApiV1TasksIdResponse = zod.void()


