/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UAlert: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.9.0_08dd63c676b9279a226fd1899e488024/node_modules/@nuxt/ui/dist/runtime/components/Alert.vue')['default']
    UApp: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.9.0_08dd63c676b9279a226fd1899e488024/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UButton: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.9.0_08dd63c676b9279a226fd1899e488024/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCheckbox: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.9.0_08dd63c676b9279a226fd1899e488024/node_modules/@nuxt/ui/dist/runtime/components/Checkbox.vue')['default']
    UForm: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.9.0_08dd63c676b9279a226fd1899e488024/node_modules/@nuxt/ui/dist/runtime/components/Form.vue')['default']
    UFormField: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.9.0_08dd63c676b9279a226fd1899e488024/node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    UInput: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.9.0_08dd63c676b9279a226fd1899e488024/node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
  }
}
