/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Gold Standard API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiV1TasksId200Data } from './getApiV1TasksId200Data';

export type GetApiV1TasksId200 = {
  data: GetApiV1TasksId200Data;
};
