/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Gold Standard API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiV1Tasks200DataItem } from './getApiV1Tasks200DataItem';
import type { GetApiV1Tasks200Meta } from './getApiV1Tasks200Meta';

export type GetApiV1Tasks200 = {
  data: GetApiV1Tasks200DataItem[];
  meta: GetApiV1Tasks200Meta;
};
