/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Gold Standard API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiV1Tasks200MetaPagination = {
  nextCursor: string | null;
  hasMore: boolean;
  limit: number;
};
