/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Gold Standard API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiV1Tasks200MetaPagination } from './getApiV1Tasks200MetaPagination';

export type GetApiV1Tasks200Meta = {
  pagination: GetApiV1Tasks200MetaPagination;
};
