/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Gold Standard API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiV1TasksParams = {
/**
 * @maximum 100
 * @exclusiveMinimum 0
 */
limit?: number;
/**
 * Opaque pagination cursor
 */
cursor?: string;
};
