/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Gold Standard API
 * OpenAPI spec version: 1.0.0
 */
import type { PatchApiV1TasksId200Data } from './patchApiV1TasksId200Data';

export type PatchApiV1TasksId200 = {
  data: PatchApiV1TasksId200Data;
};
