/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Gold Standard API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Fields to update; omitted fields are left unchanged
 */
export type PatchApiV1TasksIdBody = {
  /**
     * @minLength 1
     * @maxLength 200
     */
  title?: string;
  done?: boolean;
  dueDate?: string | null;
};
