/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Gold Standard API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiV1Tasks201Data } from './postApiV1Tasks201Data';

export type PostApiV1Tasks201 = {
  data: PostApiV1Tasks201Data;
};
