/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Gold Standard API
 * OpenAPI spec version: 1.0.0
 */

export type PostApiV1TasksBody = {
  /**
     * Task title
     * @minLength 1
     * @maxLength 200
     */
  title: string;
  /** Due date, ISO 8601 UTC */
  dueDate?: string | null;
};
