/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Gold Standard API
 * OpenAPI spec version: 1.0.0
 */
import type {
  GetApiV1Tasks200,
  GetApiV1TasksId200,
  GetApiV1TasksParams,
  PatchApiV1TasksId200,
  PatchApiV1TasksIdBody,
  PostApiV1Tasks201,
  PostApiV1TasksBody
} from './models';

import { http } from './http';

export const getGetApiV1TasksUrl = (params?: GetApiV1TasksParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/tasks?${stringifiedParams}` : `/api/v1/tasks`
}

/**
 * @summary List tasks
 */
export const getApiV1Tasks = async (params?: GetApiV1TasksParams, options?: RequestInit): Promise<GetApiV1Tasks200> => {

  return http<GetApiV1Tasks200>(getGetApiV1TasksUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}



export const getPostApiV1TasksUrl = () => {




  return `/api/v1/tasks`
}

/**
 * @summary Create a task
 */
export const postApiV1Tasks = async (postApiV1TasksBody: PostApiV1TasksBody, options?: RequestInit): Promise<PostApiV1Tasks201> => {

  return http<PostApiV1Tasks201>(getPostApiV1TasksUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(postApiV1TasksBody)
  }
);}



export const getGetApiV1TasksIdUrl = (id: string,) => {




  return `/api/v1/tasks/${id}`
}

/**
 * @summary Get a task by ID
 */
export const getApiV1TasksId = async (id: string, options?: RequestInit): Promise<GetApiV1TasksId200> => {

  return http<GetApiV1TasksId200>(getGetApiV1TasksIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}



export const getPatchApiV1TasksIdUrl = (id: string,) => {




  return `/api/v1/tasks/${id}`
}

/**
 * @summary Update a task
 */
export const patchApiV1TasksId = async (id: string,
    patchApiV1TasksIdBody: PatchApiV1TasksIdBody, options?: RequestInit): Promise<PatchApiV1TasksId200> => {

  return http<PatchApiV1TasksId200>(getPatchApiV1TasksIdUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(patchApiV1TasksIdBody)
  }
);}



export const getDeleteApiV1TasksIdUrl = (id: string,) => {




  return `/api/v1/tasks/${id}`
}

/**
 * @summary Delete a task
 */
export const deleteApiV1TasksId = async (id: string, options?: RequestInit): Promise<void> => {

  return http<void>(getDeleteApiV1TasksIdUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}



